import { Inter } from "next/font/google";
import "./globals.css";
import Heading from "@/components/Heading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Heading></Heading>
        <div className="h-screen">
        {children}
        </div>
        <footer className="bg-red-500 px-7 py-10">
          <p>Copyright © 2023 Next Hero. All rights reserved.</p>
        </footer>
        </body>
    </html>
  );
}
